version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket all-lambda-code-deploy-bucket --output-template-file outputTemplate.yaml
  build:
    commands:
      - pip install pandas

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml